function provinces() {
  return [
    { prov_code: '11', name: '北京市' }, 
    { prov_code: '12', name: '天津市' }, 
    { prov_code: '31', name: '上海市' }, 
    { prov_code: '50', name: '重庆市' }, 
    { prov_code: '81', name: '香港' }, 
    { prov_code: '82', name: '澳门' }, 
    { prov_code: '13', name: '河北省' }, 
    { prov_code: '14', name: '山西省' }, 
    { prov_code: '61', name: '陕西省' }, 
    { prov_code: '37', name: '山东省' }, 
    { prov_code: '41', name: '河南省' }, 
    { prov_code: '21', name: '辽宁省' }, 
    { prov_code: '22', name: '吉林省' }, 
    { prov_code: '23', name: '黑龙江省' }, 
    { prov_code: '32', name: '江苏省' }, 
    { prov_code: '33', name: '浙江省' }, 
    { prov_code: '34', name: '安徽省' }, 
    { prov_code: '36', name: '江西省' }, 
    { prov_code: '35', name: '福建省' }, 
    { prov_code: '42', name: '湖北省' }, 
    { prov_code: '43', name: '湖南省' }, 
    { prov_code: '51', name: '四川省' }, 
    { prov_code: '52', name: '贵州省' }, 
    { prov_code: '53', name: '云南省' }, 
    { prov_code: '44', name: '广东省' }, 
    { prov_code: '46', name: '海南省' }, 
    { prov_code: '62', name: '甘肃省' }, 
    { prov_code: '63', name: '青海省' }, 
    { prov_code: '71', name: '台湾省' }, 
    { prov_code: '15', name: '内蒙古' }, 
    { prov_code: '65', name: '新疆维吾尔' }, 
    { prov_code: '54', name: '西藏' }, 
    { prov_code: '45', name: '广西' }, 
    { prov_code: '64', name: '宁夏' }
  ]
}

module.exports = provinces