module.exports = [ //'广东'
  { city_code: '4401', name: '广州市' }, 
  { city_code: '4402', name: '韶关市' }, 
  { city_code: '4403', name: '深圳市' }, 
  { city_code: '4404', name: '珠海市' }, 
  { city_code: '4405', name: '汕头市' }, 
  { city_code: '4406', name: '佛山市' }, 
  { city_code: '4407', name: '江门市' }, 
  { city_code: '4408', name: '湛江市' }, 
  { city_code: '4409', name: '茂名市' }, 
  { city_code: '4412', name: '肇庆市' }, 
  { city_code: '4413', name: '惠州市' }, 
  { city_code: '4414', name: '梅州市' }, 
  { city_code: '4415', name: '汕尾市' }, 
  { city_code: '4416', name: '河源市' }, 
  { city_code: '4417', name: '阳江市' }, 
  { city_code: '4418', name: '清远市' }, 
  { city_code: '4419', name: '东莞市' }, 
  { city_code: '4420', name: '中山市' }, 
  { city_code: '4451', name: '潮州市' }, 
  { city_code: '4452', name: '揭阳市' }, 
  { city_code: '4453', name: '云浮市' }
]