module.exports = [ //'河南'
  { city_code: '4101', name: '郑州市' }, 
  { city_code: '4102', name: '开封市' }, 
  { city_code: '4103', name: '洛阳市' }, 
  { city_code: '4104', name: '平顶山市' }, 
  { city_code: '4105', name: '安阳市' }, 
  { city_code: '4106', name: '鹤壁市' }, 
  { city_code: '4107', name: '新乡市' }, 
  { city_code: '4108', name: '焦作市' }, 
  { city_code: '4109', name: '濮阳市' }, 
  { city_code: '4110', name: '许昌市' }, 
  { city_code: '4111', name: '漯河市' }, 
  { city_code: '4112', name: '三门峡市' }, 
  { city_code: '4113', name: '南阳市' }, 
  { city_code: '4114', name: '商丘市' }, 
  { city_code: '4115', name: '信阳市' }, 
  { city_code: '4116', name: '周口市' }, 
  { city_code: '4117', name: '驻马店市' }, 
  { city_code: '4190', name: '其他' }
]