module.exports = [ //'四川'
  { city_code: '5101', name: '成都市' }, 
  { city_code: '5103', name: '自贡市' }, 
  { city_code: '5104', name: '攀枝花市' }, 
  { city_code: '5105', name: '泸洲市' }, 
  { city_code: '5106', name: '德阳市' }, 
  { city_code: '5107', name: '绵阳市' }, 
  { city_code: '5108', name: '广元市' }, 
  { city_code: '5109', name: '遂宁市' }, 
  { city_code: '5110', name: '内江市' }, 
  { city_code: '5111', name: '乐山市' }, 
  { city_code: '5113', name: '南充市' }, 
  { city_code: '5114', name: '眉山市' }, 
  { city_code: '5115', name: '宜宾市' }, 
  { city_code: '5116', name: '广安市' }, 
  { city_code: '5117', name: '达州市' }, 
  { city_code: '5118', name: '雅安市' }, 
  { city_code: '5119', name: '巴中市' }, 
  { city_code: '5120', name: '资阳市' }, 
  { city_code: '5132', name: '阿坝自治州' }, 
  { city_code: '5133', name: '甘孜自治州' }, 
  { city_code: '5134', name: '凉山自治州' }
]